-- 04_tables.sql
-- Generated by SQL Schema Splitter
-- Contains 27 statements
-- Source: prod-declarative-301225.sql


SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."cities" (
    "id" bigint NOT NULL,
    "name" "text" NOT NULL,
    "admin1" "text",
    "country_iso2" character(2) NOT NULL,
    "country_name" "text" NOT NULL,
    "lat" double precision NOT NULL,
    "lon" double precision NOT NULL,
    "m49_region" integer,
    "m49_subregion" integer,
    "continent" "text",
    "population" integer,
    "name_norm" "text",
    "admin1_norm" "text"
);


ALTER TABLE "public"."cities" OWNER TO "postgres";



CREATE TABLE IF NOT EXISTS "public"."embeddings" (
    "entity_type" "text" NOT NULL,
    "entity_id" "text" DEFAULT "gen_random_uuid"() NOT NULL,
    "model" "text" NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"(),
    "user_id" "uuid" NOT NULL,
    "version" "text",
    "semantic_vector_ev2" "public"."vector"(1024)
);


ALTER TABLE "public"."embeddings" OWNER TO "postgres";


COMMENT ON COLUMN "public"."embeddings"."version" IS 'Iterations of the matching algorithms';



CREATE TABLE IF NOT EXISTS "public"."interactions" (
    "id" bigint NOT NULL,
    "actor_user" "uuid" NOT NULL,
    "target_user" "uuid" NOT NULL,
    "actor_current_idea" "uuid",
    "target_current_idea" "uuid",
    "action" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "timestamp_seen_by_target" timestamp with time zone,
    CONSTRAINT "interactions_action_check" CHECK (("action" = ANY (ARRAY['like'::"text", 'pass'::"text", 'blocked'::"text"])))
);


ALTER TABLE "public"."interactions" OWNER TO "postgres";


COMMENT ON COLUMN "public"."interactions"."timestamp_seen_by_target" IS 'When the interaction was displayed to the target user (i.e. the pending request is no longer unseen)';



CREATE TABLE IF NOT EXISTS "public"."logging" (
    "entry_uuid" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "timestamp" timestamp with time zone DEFAULT "now"() NOT NULL,
    "user_id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "message" "text",
    "log_level" "text"
);


ALTER TABLE "public"."logging" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."matches" (
    "id" "uuid" DEFAULT "extensions"."uuid_generate_v4"() NOT NULL,
    "user_a" "uuid" NOT NULL,
    "user_b" "uuid" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "active" boolean DEFAULT true
);


ALTER TABLE "public"."matches" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."profiles" (
    "user_id" "uuid" NOT NULL,
    "name" "text",
    "bio" "text",
    "achievements" "text",
    "avatarurl" "text",
    "region" "text",
    "timezone" "text",
    "created_at" timestamp with time zone DEFAULT "now"(),
    "is_published" boolean DEFAULT false NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "city_id" bigint,
    "experience" "text",
    "education" "text"
);


ALTER TABLE "public"."profiles" OWNER TO "postgres";


COMMENT ON COLUMN "public"."profiles"."is_published" IS 'Whether the profile is public and visible';



COMMENT ON COLUMN "public"."profiles"."updated_at" IS 'Timestamp of last update of core user data';



CREATE TABLE IF NOT EXISTS "public"."user_cofounder_preference" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "title" "text" NOT NULL,
    "description" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."user_cofounder_preference" OWNER TO "postgres";


COMMENT ON COLUMN "public"."user_cofounder_preference"."updated_at" IS 'Timestamp of last update';



CREATE TABLE IF NOT EXISTS "public"."user_settings" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid" DEFAULT "auth"."uid"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "similarity_threshold" integer DEFAULT 2,
    "region_scope" "text" DEFAULT 'subregion'::"text",
    CONSTRAINT "user_settings_region_scope_check" CHECK (("region_scope" = ANY (ARRAY['city'::"text", 'country'::"text", 'region'::"text", 'worldwide'::"text"])))
);


ALTER TABLE "public"."user_settings" OWNER TO "postgres";


COMMENT ON TABLE "public"."user_settings" IS 'Store a user''s sesstings / preferences';



CREATE TABLE IF NOT EXISTS "public"."user_ventures" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "title" "text" NOT NULL,
    "description" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."user_ventures" OWNER TO "postgres";


COMMENT ON COLUMN "public"."user_ventures"."updated_at" IS 'Timestamp of last update';