-- 05_sequences.sql
-- Generated by SQL Schema Splitter
-- Contains 6 statements
-- Source: prod-declarative-301225.sql



CREATE SEQUENCE IF NOT EXISTS "public"."cities_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."cities_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."cities_id_seq" OWNED BY "public"."cities"."id";



CREATE SEQUENCE IF NOT EXISTS "public"."interactions_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."interactions_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."interactions_id_seq" OWNED BY "public"."interactions"."id";