-- 07_indexes.sql
-- Generated by SQL Schema Splitter
-- Contains 15 statements
-- Source: prod-declarative-301225.sql




CREATE INDEX "cities_admin1_trgm" ON "public"."cities" USING "gin" ("admin1_norm" "public"."gin_trgm_ops");



CREATE INDEX "cities_country" ON "public"."cities" USING "btree" ("country_iso2");



CREATE INDEX "cities_name_trgm" ON "public"."cities" USING "gin" ("name" "public"."gin_trgm_ops");



CREATE INDEX "cities_subregion" ON "public"."cities" USING "btree" ("m49_subregion");



CREATE UNIQUE INDEX "cities_unique" ON "public"."cities" USING "btree" ("name", "admin1", "country_iso2");



CREATE INDEX "embeddings_semantic_vector_ev2_hnsw_idx" ON "public"."embeddings" USING "hnsw" ("semantic_vector_ev2" "public"."vector_ip_ops") WITH ("m"='16', "ef_construction"='64');



CREATE INDEX "ix_interactions_actor_target" ON "public"."interactions" USING "btree" ("actor_user", "target_user") WHERE ("action" = ANY (ARRAY['like'::"text", 'pass'::"text"]));



CREATE INDEX "ix_interactions_blocked_pair" ON "public"."interactions" USING "btree" (LEAST("actor_user", "target_user"), GREATEST("actor_user", "target_user")) WHERE ("action" = 'block'::"text");



CREATE UNIQUE INDEX "ix_interactions_blocked_pair_once" ON "public"."interactions" USING "btree" (LEAST("actor_user", "target_user"), GREATEST("actor_user", "target_user")) WHERE ("action" = 'block'::"text");



CREATE INDEX "ix_interactions_incoming_like" ON "public"."interactions" USING "btree" ("target_user", "created_at" DESC) WHERE ("action" = 'like'::"text");



CREATE INDEX "ix_interactions_my_like" ON "public"."interactions" USING "btree" ("actor_user", "target_user") WHERE ("action" = 'like'::"text");



CREATE INDEX "ix_interactions_pass_window" ON "public"."interactions" USING "btree" ("actor_user", "target_user", "created_at" DESC) WHERE ("action" = 'pass'::"text");



CREATE UNIQUE INDEX "ix_interactions_unidir_once" ON "public"."interactions" USING "btree" ("actor_user", "target_user", "action") WHERE ("action" = ANY (ARRAY['like'::"text", 'pass'::"text"]));



CREATE INDEX "ix_matches_pair_active" ON "public"."matches" USING "btree" (LEAST("user_a", "user_b"), GREATEST("user_a", "user_b")) WHERE "active";



CREATE UNIQUE INDEX "matches_unique_pair" ON "public"."matches" USING "btree" (LEAST("user_a", "user_b"), GREATEST("user_a", "user_b"));