-- 08_triggers.sql
-- Generated by SQL Schema Splitter
-- Contains 1 statements
-- Source: prod-declarative-301225.sql




CREATE OR REPLACE TRIGGER "trg_cities_norm" BEFORE INSERT OR UPDATE ON "public"."cities" FOR EACH ROW EXECUTE FUNCTION "public"."cities_norm_trg"();